apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: backend-service
  labels:
    app: backend-deployment
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    name: backend-deployment
    app: backend-deployment
  type: ClusterIP