apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: bobor16/simple-fortune-cookie-backend:c7d76f134cf9779e6f5a70732605b792535e269e
        name: simple-fortune-cookie-backend
        imagePullPolicy: Always
        resources: {}