apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-deployment
  type: NodePort
status:
  loadBalancer: {}