apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database-deployment
      app: database-deployment
  template:
    metadata:
      labels:
        name: database-deployment
        app: database-deployment
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redis
        ports:
            - containerPort: 6379
        resources: {}
status: {}