apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database-deployment
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database-deployment
    spec:
      containers:
      - image: redis
        name: database