apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-deployment
  name: database-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: database-deployment
  type: NodePort
status:
  loadBalancer: {}