apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: database-service
  labels:
    app: database-deployment
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: database-deployment
    app: database-deployment
  type: ClusterIP