apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend-service
  labels:
    app: frontend-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: frontend-deployment
    app: frontend-deployment
  type: NodePort