apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: bobor16/simple-fortune-cookie-frontend:latest
        name: simple-fortune-cookie-frontend
        imagePullPolicy: Always
        resources: {}