name: Go

on:
  push:
  pull_request:

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: ./frontend

  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build
        working-directory: ./frontend

      - name: Test
        run: go test
        working-directory: ./frontend

  DockerImage-frontend:
    runs-on: ubuntu-latest
    needs: [Build, Tests]
    steps:
      - name: Download artifact code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ env.docker_username }}/simple-fortune-cookie-frontend

  
  DockerImage-backend:
    runs-on: ubuntu-latest
    needs: [Build, Tests]
    steps:
      - name: Download artifact code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ env.docker_username }}/simple-fortune-cookie-backend

  Tests:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: ./frontend && ./backend

  Test-frontend:
    runs-on: self-hosted
    needs: [Build, DockerImage-frontend]
    container: golang:latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - uses: actions/checkout@v2
      - name: run test
        run: cd ./ci && chmod +x frontend-test.sh && ./frontend-test.sh

  Test-backend:
    runs-on: self-hosted
    needs: [Build, DockerImage-backend]
    container: golang:latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - uses: actions/checkout@v2
      - name: run test
        run: cd ./ci && chmod +x backend-test.sh && ./backend-test.sh

  Test-runner:
    runs-on: self-hosted
    needs: Clone-down
    container: golang:latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: run test
        run: cd ./ci && chmod +x test.sh && ./test.sh
