name: Go

on:
  push:
  pull_request:

jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: ./frontend

  push_to_registry:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
      - name: Download code
        uses: actions/download-artifact@v1
        with:
          name: code
          path: ./frontend
      - name: build docker
        run: chmod +x ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
      - name: push docker
        run: chmod +x ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh

  Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: ./frontend && ./backend

  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build
        working-directory: ./frontend

      - name: Test
        run: go test
        working-directory: ./frontend
