name: Go

on:
  push:
    branches: [automation]
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: ./frontend
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build
        working-directory: ./frontend

      - name: Test
        run: go test
        working-directory: ./frontend
