name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd /home/ubuntu/AwesomeProject/simple-fortune-cookie/backend && go build && go tidy

    - name: Test
      run: cd test && go test -v
